### ISSUE TITLE
value sql is not a member of StringContext

### ISSUE THREAD

**Issue by clarkliu20083736** [koeninger/kafka-exactly-once#11]
Hi,

I am a beginner of using kafka.

I am using Intranet , so I down the jars manual.

The I found a error in intellij idea.
![20170605171928](https://cloud.githubusercontent.com/assets/20986311/26778281/2faf167e-4a13-11e7-8ec4-91edca024e35.png)

Because i am using Intranet, so I download the jar files manually.
This is the screenshot of my jars.
![20170605172642](https://cloud.githubusercontent.com/assets/20986311/26778524/3273c5a2-4a14-11e7-8302-5f1397f83c9b.png)

could you please tell me what i am doing wrong?

Thank you in advance.

Best wishes,
Clark Liu

**Comment by koeninger** [comment]
If you look at build.sbt, the examples have a dependency on scalikejdbc, which is what is providing the sql string interpolation.

You can modify it to use whatever means of communicating with jdbc you want.

**Comment by clarkliu20083736** [comment]
Hi koeninger,

Thank you for your answer.
Base on your suggestion,I have resolved the issue.

Best wishes,
Clark Liu

**Comment by y2k-shubham** [comment]
@koeninger could you please elaborate your solution? I'm new to development, I didn't understand even a bit of it.

I have added `ScalikeJdbc` in my _dependencies_, and _sql interpolation_ for `MySQL` querying is working just fine elsewhere in my project, except for this one occurence.

Earlier I had a method by the name `sql` in the _same scope_, but now even after having renamed that method, this error is showing up upon running `sbt compile`.

**Comment by hartmut27** [comment]
adding 

> import scalikejdbc._

removes the errmor message 

> value sql is not a member of StringContext

in my case
