### ISSUE TITLE
multiple kafka clusters

### ISSUE THREAD

**Issue by mazorigal** [koeninger/kafka-exactly-once#12]
Hi,

we have 2 data center, each having its own kafka cluster. I would like to have spark streaming job that consumes from both of those kafka clusters. Is that possible at all ?
I tried to create 2 kafka direct streams sources, but eventually got an error that kafka consumer is not thread safe:
```Caused by: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access```
I assume that because each kafka direct stream creates separate consumer, and those 2 consumers are started on same worker - same thread.

Thanks,

**Comment by koeninger** [comment]
Are you using the same consumer group for both?  The docs say to use a
separate consumer group per stream.  Reason for this being the key for the
cache of consumers uses group.

**Comment by mazorigal** [comment]
Thanks, that indeed solved the issue.
