### ISSUE TITLE
Processing Backlog Of Direct Stream

### ISSUE THREAD

**Issue by ariens** [koeninger/kafka-exactly-once#4]
Hi Cody, 
- Spark 1.6.0
- Kafka 0.9.0 (using 0.8.2.2 API and client libraries in Spark)

Excellent blog post, I've been playing around with direct streaming for a little while now and I have some questions.  My use case is to consume all partitions from one or more topic using a custom value decoder which creates a stream of [Point](https://github.com/paulgoldbaum/scala-influxdb-client/blob/master/src/main/scala/com/paulgoldbaum/influxdbclient/Point.scala) objects that I then [bulk write](https://github.com/paulgoldbaum/scala-influxdb-client/blob/master/src/main/scala/com/paulgoldbaum/influxdbclient/Database.scala#L22) to an Influx DB cluster.  

I wrote a utility, [Korpse](https://gist.github.com/ariens/e6a39bc3dbeb11467e53), that stores/fetches offsets in Kafka.  When there is no backlog, this solution works really well and I process my events in 30 second batches.  

``` scala
    val fromOffsets = korpse.getFromOffsets()
    if (!fromOffsets.isDefined) {
      LOG.error("Unable to determine starting offsets")
      System.exit(1)
    }

    var offsetRanges = Array[OffsetRange]()

    val stream = KafkaUtils.createDirectStream[String, Point, StringDecoder, PointDecoder, (Point)](ssc, kafkaParams, fromOffsets.get,
      (mmd: MessageAndMetadata[String, Point]) => (
        mmd.message()))
      .transform { rdd =>
        offsetRanges = rdd.asInstanceOf[HasOffsetRanges].offsetRanges
        rdd
      }

    stream.foreachRDD { rdd =>
      rdd.foreachPartition { partitionOfRecords =>
        val influxdb = InfluxDB.connect("influxdb-1.lab, 8086)
        val database = influxdb.selectDatabase("rsyslog-stats-test1")
        val points = partitionOfRecords.toList
        println("there are " + points.size + " points in the total list")
        val batchSize = 4500
        var x = 0
        for (x <- 0 to points.size by batchSize) {
          val end = if (x + batchSize < (points.size - 1)) x + batchSize else points.size
          println("about to send batch " + x + " to " + end)
          database.bulkWrite(points.slice(x, end).toList, precision = Precision.SECONDS)
            .onComplete {
              case Success(b) => println(s"sent batch $x to $end")
              case Failure(t) => println(s"failed to sent batch $x to $end: " + t.getMessage)
            }
        }        
      }
    }

    stream.foreachRDD { rdd =>
      korpse.storeOffsetRanges(offsetRanges)
    }    
```

With a single topic/partition Kafka receives around 1000 events per second so a 20s micro batch in Spark works rather well.  However, when there are a significant amount of offsets (10's of millions or more) in the backlog because either the Spark application died or hadn't been running for some time, the first Spark job processes the entirety of the backlog and often runs out of memory or takes a very long time.  

Is there an out-of-the-box method to have consuming distributed across all executors even if there is only a single partition of a single topic being consumed?

Ideally, I'd like to distribute the processing of the backlog across all executors, for the first batch but also all subsequent batches.

I.e. if there are 5 executors and 3 TopicAndPartition's that receive 1000 events/sec each, each executor should consume/process 12 000 events for each micro batch.

I don't mind enhancing my Korpse util and converting to Kafka createKafkaRdd with OffsetRange accordingly but I thought I'd enquire with someone like you who knows way more about Spark before starting...

**Comment by koeninger** [comment]
If you're running out of memory because of too many items in a batch, see

http://spark.apache.org/docs/latest/configuration.html#spark-streaming

specifically spark.streaming.kafka.maxRatePerPartition

If you want to mess around with consuming the same topicpartition from
multiple executors, you can certainly try to do so using KafkaRDD.  I
don't think it's generally a good idea though, and am not all that
interested in trying to add an automated way to do it in streaming.  I
think it's better to repartition kafka, or explicitly shuffle.

**Comment by ariens** [comment]
By re-partitioning kafka I expect you mean increasing the number of partitions which would then naturally increase the parallelism in Spark?   I'm not opposed to that however my instinct is to only up partition count in Kafka when ingest becomes the bottleneck.    Can you elaborate on the explicit shuffle and how Spark would better distribute the first job?If I rate limit the fetch requests that only makes the first job slower before eventually running out of memory, no?  That first job will still create the RDD of the backlog for the entirety of the offsets from last persisted offset to latest in a single thread, wouldn't it? In my scenario that could be 10s of millions if the job is down for a few hours....

**Comment by koeninger** [comment]
Yes, I mean increasing kafka partitions.  Kafka read parallelism is
fundamentally limited to 1 thread per partition, this isn't a spark-only
thing.

Rate limiting in this case sets a maximum batch size (i.e. number of
offsets per rdd partition).  So no if you set that limit appropriately you
won't run out of memory, as long as you aren't aggregating across batches.

**Comment by ariens** [comment]
I didn't understand how the rat limit applied to the Kafka direct stream, thanks for clarifying. Yes. That would prevent the OOM issues but playing catch up could still potentially take a very long time.   Just out of curiosity is the RDD to Kafka partition relationship a design goal to preserve ordering? Is this a direct streaming-ism in general? I can think of a few use cases where it would would handy to throw a large number of executors at some Kafka partitions and have RDDs created that consume evenly from the requested offsets for the batch duration then proceed to processing. Or is that where the KafkaRDD approach comes in?

**Comment by koeninger** [comment]
Yes it's to preserve ordering. That's how Kafka is designed, doesn't really
have anything to do with spark.

If you dont care about ordering, don't want to add Kafka partitions,  and
the time you're spending is compute limited, not io reading from Kafka, you
may benefit from shuffling (repartition in spark).

**Comment by ariens** [comment]
Is that as easy as `stream.repartition(x: int)`?

**Comment by koeninger** [comment]
Yeah. You just need try with and without repartition to see whether its
worth the shuffle overhead.

**Comment by ariens** [comment]
Thanks for all the advice!
