### ISSUE TITLE
Dstream mapWithState

### ISSUE THREAD

**Issue by mazorigal** [koeninger/kafka-exactly-once#9]
Hi,

according to spark docs:
https://spark.apache.org/docs/2.1.0/streaming-kafka-0-10-integration.html

If I would like to commit offsets to kafka (for at least once semantic) the way to go is as following:

```
stream.foreachRDD { rdd =>
  val offsetRanges = rdd.asInstanceOf[HasOffsetRanges].offsetRanges

  // some time later, after outputs have completed

  stream.asInstanceOf[CanCommitOffsets].commitAsync(offsetRanges)
}
```

The problem is that then I have to apply all my logic for each RDD in the Dstream inside the foreachRDD block, however then I could no use mapWithState since it works only with Dstream and the type of the rdd inside the foreachRDD block is simple RDD.

Do I miss something ? is there any workaround ?

Thanks,

**Comment by koeninger** [comment]
You can try using .transform as described in

https://spark.apache.org/docs/2.1.0/streaming-kafka-0-8-integration.html#approach-2-direct-approach-no-receivers

Can't guarantee that's going to work in all cases, but try it and see if it works for what you're doing.
